export enum RootGetters {
  UPDATE_VERSION = "UPDATE_VERSION"
}
export enum RootMutations {
  UPDATE_VERSION = "UPDATE_VERSION"
}
export enum RootActions {
  UPDATE_VERSION = "UPDATE_VERSION"
}

export enum SourceGetters {
  SOURCES = "SOURCES"
}

export enum SourceMutations {
  SET_SOURCES = "SET_SOURCES",
  DELETE_SOURCES = "DELETE_SOURCES",
  UPDATE_SOURCE = "UPDATE_SOURCE"
}

export enum SourceActions {
  GET_SOURCES = "GET_SOURCES",
  CREATE_SOURCE = "CREATE_SOURCE",
  DELETE_SOURCES = "DELETE_SOURCES",
  UPDATE_SOURCE = "UPDATE_SOURCE"
}

export enum TypeGetters {
  TYPES = "TYPES"
}

export enum TypeMutations {
  SET_TYPES = "SET_TYPES",
  DELETE_TYPES = "DELETE_TYPES",
  UPDATE_TYPE = "UPDATE_TYPE"
}

export enum TypeActions {
  GET_TYPES = "GET_TYPES",
  CREATE_TYPE = "CREATE_TYPE",
  DELETE_TYPES = "DELETE_TYPES",
  UPDATE_TYPE = "UPDATE_TYPE"
}

export enum CategoryGetters {
  CATEGORIES = "CATEGORIES"
}

export enum CategoryMutations {
  SET_CATEGORIES = "SET_CATEGORIES",
  DELETE_CATEGORIES = "DELETE_CATEGORIES",
  UPDATE_CATEGORY = "UPDATE_CATEGORY"
}

export enum CategoryActions {
  GET_CATEGORIES = "GET_CATEGORIES",
  CREATE_CATEGORY = "CREATE_CATEGORY",
  DELETE_CATEGORIES = "DELETE_CATEGORIES",
  UPDATE_CATEGORY = "UPDATE_CATEGORY"
}

export enum SubcategoryGetters {
  SUBCATEGORIES = "SUBCATEGORIES"
}

export enum SubcategoryMutations {
  SET_SUBCATEGORIES = "SET_SUBCATEGORIES",
  DELETE_SUBCATEGORIES = "DELETE_SUBCATEGORIES",
  UPDATE_SUBCATEGORY = "UPDATE_SUBCATEGORY"
}

export enum SubcategoryActions {
  GET_SUBCATEGORIES = "GET_SUBCATEGORIES",
  CREATE_SUBCATEGORY = "CREATE_SUBCATEGORY",
  DELETE_SUBCATEGORIES = "DELETE_SUBCATEGORIES",
  UPDATE_SUBCATEGORY = "UPDATE_SUBCATEGORY"
}

export enum OperationGetters {
  OPERATIONS = "OPERATIONS"
}

export enum OperationMutations {
  SET_OPERATIONS = "SET_OPERATIONS",
  DELETE_OPERATIONS = "DELETE_OPERATIONS",
  UPDATE_OPERATION = "UPDATE_OPERATION"
}

export enum OperationActions {
  GET_OPERATIONS = "GET_OPERATIONS",
  CREATE_OPERATION = "CREATE_OPERATION",
  DELETE_OPERATIONS = "DELETE_OPERATIONS",
  UPDATE_OPERATION = "UPDATE_OPERATION"
}
